# coding: utf-8

# flake8: noqa
"""
    Open API, powered by Buildium

      # Introduction  ### Welcome!    Welcome to Buildium’s API—a powerful, RESTful programming interface that lets you leverage valuable Buildium data.    Using HTTP requests, you can create integrations with applications that specialize in accounting, lead tracking, and more. Enjoy greater flexibility, transparency, and control over your business!      ### What's in this Guide?    This guide is full of simple, easy-to-follow instructions that’ll help you use Buildium’s API like a pro.    Topics include:    * choosing the right resources for your use case  * making HTTP requests to any resource  * understanding data and response codes    <br />    # Getting Started  Excited to get going? We’ll walk you through the setup process.  >  **Note:** To take advantage of the Buildium Open API you must have a <a target=\"_blank\" href=\"https://www.buildium.com/pricing/\">**Premium Subscription**</a>.    ## Account Configuration  Before you can use Buildium’s API, you’ll need to make some tweaks to your account settings.    <br />    ### Enabling the API  In order to start creating your keys and making requests, you’ll need to enable the API.      >  **Tip:** You’ll need an administrator user role with access to ***Application settings*** to set things up properly.    <br />    ​ **Let's Begin!**    1. Sign in to your [Buildium](https://signin.managebuilding.com/manager/public/authentication/login?ReturnUrl=%2Fmanager%2F) account from your browser.    2. Open the ***Settings*** menu and click ***Application settings***.    3. Under ***System preferences***, click ***Api settings***. A modal will appear.    4. Click the ***Open API*** toggle to turn it on. Then click ***Save***.    <video width=\"100%\" autoplay loop muted>    <source src=\"enable_open_api.mp4\" type=\"video/mp4\" />  </video>      Congratulations! Your account's enabled. Now, you’re ready to start managing API keys.  <br />  <br />  If you are having issues enabling the API within your account you can submit a [Support](#section/API-Overview/Support) request for assistance.    <br />      ## API Keys  Account-level API keys authenticate every request and keep things secure.    API keys have two components: a “client ID” and a “secret”.    * **Client IDs** are similar to usernames. They’re used to identify your Buildium account and are safe to share.  * **Secrets** are similar to passwords. They must be kept confidential.    Whenever you make a request, you’ll need the API key’s client ID and secret. If you forget it, make a mistake, or try to use information that’s linked to a deleted key, the API will return a `401` response code.    >  **Tip:** We compiled a list of best practices that detail how securely store API keys. [Give it a read](#section/Getting-Started/Keeping-API-Keys-Safe)!    ## Creating API Keys  Now that the Open APi is enabled, you’ll be able to create API keys. You’re almost there!    >  **Tip:** You’ll need an administrator user role to complete this step, too.    <br />    **How to create an API key**    1. Sign in to your [Buildium](https://signin.managebuilding.com/manager/public/authentication/login?ReturnUrl=%2Fmanager%2F) account from your browser.    2. Open the ***Settings*** menu and click ***Developer Tools***. The page will open automatically.    3. Click the ***Create API Key*** button. A modal will appear.    4. Enter a clear, memorable name and description for your API key. It’ll make it easier to locate the right key when you make a request. Once finished, click **Next**.    5. Now, choose which pieces of Buildium data you want this API key to have access to by marking the corresponding checkboxes. Once finished, click **Next**.    6. You successfully created an API key!    > **Important:** This is your only chance to record the secret. Make sure it’s stored somewhere secure! If it’s forgotten, you’ll need to delete this key and start from scratch.    <br />    <video width=\"100%\" autoplay loop muted>    <source src=\"generate_open_api_key.mp4\" type=\"video/mp4\" />  </video>    <br />    You have now successfully created an API key and have everything you need to  send requests to the Buildium API!    Before moving on to [making your first request](#section/Getting-Started/How-to-Make-a-Request) please review [Keeping your Keys Safe](#section/Getting-Started/Keeping-your-Keys-Safe) for an overview on securely storing your API keys.    <br />  If you are having issues creating API keys you can submit a [Support](#section/API-Overview/Support) request for assistance.  <br />      ## Keeping API Keys Safe    Based on their permissions, API keys could have full access to your account’s Buildium data. It’s important that you only grant access to trusted applications, securely record secrets, and consider a password manager to stay organized.      ### Recommended Practices    - Avoid hard-coding client IDs and secrets inside source files.  - Avoid storing client IDs and secrets in any files that may be committed to source control, particularly cloud-based source control platforms.  - Apply restrictions to client IDs and secrets shared with your staff. You can restrict a key to particular Buildium entities or to read-only access (GET resources only).  - Avoid sharing client IDs and secrets across public, insecure platforms.  - Establish a process to regularly recreate your client IDs and secrets from your Buildium account.    <br />    <br />    ## How to Make a Request    You’ve done a great job setting up your account, Now, we’ll walk you through how to access your data. It’s very straightforward and should only take a few minutes!      > **Tip:** Looking for the right HTTP client? If you’re just getting started, we recommend Postman.      <br />    ### Let's Get Started!    #### Step 1: Get Your API Key    If you haven't yet done so, obtain your API key client ID and secret from your Buildium account. Your API key is how the Buildium API authenticates requests and ensures only you can access your data.    See [Getting Started](#section/Getting-Started) for a deeper dive into enabling the API and creating keys.    #### Step 2: Install a HTTP client  The Buildium API supports any standard HTTP client. If you're looking for a user-friendly HTTP client application, we recommend [Postman](https://www.postman.com/product/api-client) – it allows you to access the Buildium API without writing code. We’ll use Postman for our example below to demonstrate sending an API request.      #### Step 3: Make a Sample Request    Let's dive in and make a simple request to get all the [Rental Properties](#operation/RentalsGetAllGLAccounts) response message now includes the property `IsBankAccount`. This is a boolean property that indicates whether the general ledger account is also a bank account.  * A `Country` property has been added to all Address messages. This property contains an enumeration indicating the country of the address.   

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.account_info_message import AccountInfoMessage
from openapi_client.models.accounting_entity_message import AccountingEntityMessage
from openapi_client.models.accounting_entity_patch_message import AccountingEntityPatchMessage
from openapi_client.models.accounting_entity_save_message import AccountingEntitySaveMessage
from openapi_client.models.accounting_lock_period_message import AccountingLockPeriodMessage
from openapi_client.models.accounting_settings_message import AccountingSettingsMessage
from openapi_client.models.address_message import AddressMessage
from openapi_client.models.all_tasks_message import AllTasksMessage
from openapi_client.models.announcement_message import AnnouncementMessage
from openapi_client.models.announcement_post_message import AnnouncementPostMessage
from openapi_client.models.announcement_sender_message import AnnouncementSenderMessage
from openapi_client.models.api_error import ApiError
from openapi_client.models.api_error_response import ApiErrorResponse
from openapi_client.models.appliance_message import ApplianceMessage
from openapi_client.models.applicant_application_message import ApplicantApplicationMessage
from openapi_client.models.applicant_group_message import ApplicantGroupMessage
from openapi_client.models.applicant_group_post_message import ApplicantGroupPostMessage
from openapi_client.models.applicant_group_put_message import ApplicantGroupPutMessage
from openapi_client.models.applicant_message import ApplicantMessage
from openapi_client.models.applicant_post_message import ApplicantPostMessage
from openapi_client.models.applicant_put_message import ApplicantPutMessage
from openapi_client.models.application_message import ApplicationMessage
from openapi_client.models.application_put_message import ApplicationPutMessage
from openapi_client.models.application_response_field_message import ApplicationResponseFieldMessage
from openapi_client.models.application_response_message import ApplicationResponseMessage
from openapi_client.models.application_section_response_message import ApplicationSectionResponseMessage
from openapi_client.models.applied_vendor_credit_message import AppliedVendorCreditMessage
from openapi_client.models.architectural_requests_post_message import ArchitecturalRequestsPostMessage
from openapi_client.models.association_appliance_message import AssociationApplianceMessage
from openapi_client.models.association_appliance_post_message import AssociationAppliancePostMessage
from openapi_client.models.association_appliance_put_message import AssociationAppliancePutMessage
from openapi_client.models.association_appliance_service_history_message import AssociationApplianceServiceHistoryMessage
from openapi_client.models.association_appliance_service_history_post_message import AssociationApplianceServiceHistoryPostMessage
from openapi_client.models.association_architectural_request_file_message import AssociationArchitecturalRequestFileMessage
from openapi_client.models.association_architectural_request_message import AssociationArchitecturalRequestMessage
from openapi_client.models.association_board_member_message import AssociationBoardMemberMessage
from openapi_client.models.association_board_member_post_message import AssociationBoardMemberPostMessage
from openapi_client.models.association_board_member_put_message import AssociationBoardMemberPutMessage
from openapi_client.models.association_message import AssociationMessage
from openapi_client.models.association_owner_board_term_message import AssociationOwnerBoardTermMessage
from openapi_client.models.association_owner_board_term_post_message import AssociationOwnerBoardTermPostMessage
from openapi_client.models.association_owner_message import AssociationOwnerMessage
from openapi_client.models.association_owner_post_message import AssociationOwnerPostMessage
from openapi_client.models.association_owner_put_message import AssociationOwnerPutMessage
from openapi_client.models.association_owner_to_existing_ownership_account_post_message import AssociationOwnerToExistingOwnershipAccountPostMessage
from openapi_client.models.association_owner_unit_occupancy_put_message import AssociationOwnerUnitOccupancyPutMessage
from openapi_client.models.association_owner_unit_occupancy_status_message import AssociationOwnerUnitOccupancyStatusMessage
from openapi_client.models.association_ownership_account_message import AssociationOwnershipAccountMessage
from openapi_client.models.association_ownership_account_post_message import AssociationOwnershipAccountPostMessage
from openapi_client.models.association_ownership_account_put_message import AssociationOwnershipAccountPutMessage
from openapi_client.models.association_post_message import AssociationPostMessage
from openapi_client.models.association_preferred_vendor_message import AssociationPreferredVendorMessage
from openapi_client.models.association_preferred_vendor_put_message import AssociationPreferredVendorPutMessage
from openapi_client.models.association_put_message import AssociationPutMessage
from openapi_client.models.association_tax_information_message import AssociationTaxInformationMessage
from openapi_client.models.association_tenant_message import AssociationTenantMessage
from openapi_client.models.association_tenant_post_message import AssociationTenantPostMessage
from openapi_client.models.association_tenant_put_message import AssociationTenantPutMessage
from openapi_client.models.association_unit_message import AssociationUnitMessage
from openapi_client.models.association_unit_put_message import AssociationUnitPutMessage
from openapi_client.models.association_units_post_message import AssociationUnitsPostMessage
from openapi_client.models.bank_account_check_accounting_entity_save_message import BankAccountCheckAccountingEntitySaveMessage
from openapi_client.models.bank_account_check_file_message import BankAccountCheckFileMessage
from openapi_client.models.bank_account_check_line_message import BankAccountCheckLineMessage
from openapi_client.models.bank_account_check_line_save_message import BankAccountCheckLineSaveMessage
from openapi_client.models.bank_account_check_message import BankAccountCheckMessage
from openapi_client.models.bank_account_check_payee_message import BankAccountCheckPayeeMessage
from openapi_client.models.bank_account_check_payee_save_message import BankAccountCheckPayeeSaveMessage
from openapi_client.models.bank_account_check_post_message import BankAccountCheckPostMessage
from openapi_client.models.bank_account_check_put_message import BankAccountCheckPutMessage
from openapi_client.models.bank_account_deposit_line_message import BankAccountDepositLineMessage
from openapi_client.models.bank_account_deposit_line_save_message import BankAccountDepositLineSaveMessage
from openapi_client.models.bank_account_deposit_message import BankAccountDepositMessage
from openapi_client.models.bank_account_deposit_post_message import BankAccountDepositPostMessage
from openapi_client.models.bank_account_deposit_put_message import BankAccountDepositPutMessage
from openapi_client.models.bank_account_message import BankAccountMessage
from openapi_client.models.bank_account_post_message import BankAccountPostMessage
from openapi_client.models.bank_account_put_message import BankAccountPutMessage
from openapi_client.models.bank_account_quick_deposit_message import BankAccountQuickDepositMessage
from openapi_client.models.bank_account_quick_deposit_save_message import BankAccountQuickDepositSaveMessage
from openapi_client.models.bank_account_reconciliation_balance_message import BankAccountReconciliationBalanceMessage
from openapi_client.models.bank_account_reconciliation_balance_put_message import BankAccountReconciliationBalancePutMessage
from openapi_client.models.bank_account_reconciliation_message import BankAccountReconciliationMessage
from openapi_client.models.bank_account_reconciliation_transaction_message import BankAccountReconciliationTransactionMessage
from openapi_client.models.bank_account_transaction_message import BankAccountTransactionMessage
from openapi_client.models.bank_account_transfer_accounting_entity_save_message import BankAccountTransferAccountingEntitySaveMessage
from openapi_client.models.bank_account_transfer_message import BankAccountTransferMessage
from openapi_client.models.bank_account_transfer_save_message import BankAccountTransferSaveMessage
from openapi_client.models.bank_account_withdrawal_message import BankAccountWithdrawalMessage
from openapi_client.models.bank_account_withdrawal_save_message import BankAccountWithdrawalSaveMessage
from openapi_client.models.bank_lockbox_data_association_message import BankLockboxDataAssociationMessage
from openapi_client.models.bank_lockbox_data_association_owner_message import BankLockboxDataAssociationOwnerMessage
from openapi_client.models.bank_lockbox_data_message import BankLockboxDataMessage
from openapi_client.models.bank_lockbox_data_ownership_account_message import BankLockboxDataOwnershipAccountMessage
from openapi_client.models.bank_pending_reconciliation_post_message import BankPendingReconciliationPostMessage
from openapi_client.models.bank_reconciliation_clear_transactions_post_message import BankReconciliationClearTransactionsPostMessage
from openapi_client.models.bank_reconciliation_cleared_balance_message import BankReconciliationClearedBalanceMessage
from openapi_client.models.bank_reconciliation_put_message import BankReconciliationPutMessage
from openapi_client.models.bank_reconciliation_statement_balance_message import BankReconciliationStatementBalanceMessage
from openapi_client.models.bank_reconciliation_unclear_transactions_post_message import BankReconciliationUnclearTransactionsPostMessage
from openapi_client.models.bill_file_message import BillFileMessage
from openapi_client.models.bill_line_item_patch_message import BillLineItemPatchMessage
from openapi_client.models.bill_line_message import BillLineMessage
from openapi_client.models.bill_line_post_message import BillLinePostMessage
from openapi_client.models.bill_line_put_message import BillLinePutMessage
from openapi_client.models.bill_markup_message import BillMarkupMessage
from openapi_client.models.bill_markup_patch_message import BillMarkupPatchMessage
from openapi_client.models.bill_markup_save_message import BillMarkupSaveMessage
from openapi_client.models.bill_message import BillMessage
from openapi_client.models.bill_patch_message import BillPatchMessage
from openapi_client.models.bill_payment_accounting_entity_message import BillPaymentAccountingEntityMessage
from openapi_client.models.bill_payment_line_message import BillPaymentLineMessage
from openapi_client.models.bill_payment_line_post_message import BillPaymentLinePostMessage
from openapi_client.models.bill_payment_message import BillPaymentMessage
from openapi_client.models.bill_payment_post_message import BillPaymentPostMessage
from openapi_client.models.bill_post_message import BillPostMessage
from openapi_client.models.bill_put_message import BillPutMessage
from openapi_client.models.budget_details_message import BudgetDetailsMessage
from openapi_client.models.budget_details_save_message import BudgetDetailsSaveMessage
from openapi_client.models.budget_message import BudgetMessage
from openapi_client.models.budget_monthly_amounts_message import BudgetMonthlyAmountsMessage
from openapi_client.models.budget_monthly_amounts_save_message import BudgetMonthlyAmountsSaveMessage
from openapi_client.models.budget_post_message import BudgetPostMessage
from openapi_client.models.budget_put_message import BudgetPutMessage
from openapi_client.models.cc_payments_message import CCPaymentsMessage
from openapi_client.models.cc_payments_put_message import CCPaymentsPutMessage
from openapi_client.models.charge_recurring_transaction_post_message import ChargeRecurringTransactionPostMessage
from openapi_client.models.charge_recurring_transaction_put_message import ChargeRecurringTransactionPutMessage
from openapi_client.models.check_printing_info_message import CheckPrintingInfoMessage
from openapi_client.models.check_printing_info_post_message import CheckPrintingInfoPostMessage
from openapi_client.models.check_printing_info_put_message import CheckPrintingInfoPutMessage
from openapi_client.models.client_lead_credit_request_message import ClientLeadCreditRequestMessage
from openapi_client.models.client_lead_message import ClientLeadMessage
from openapi_client.models.contact_detail_message import ContactDetailMessage
from openapi_client.models.contact_detail_phone_message import ContactDetailPhoneMessage
from openapi_client.models.contact_detail_save_message import ContactDetailSaveMessage
from openapi_client.models.contact_detail_save_phone_message import ContactDetailSavePhoneMessage
from openapi_client.models.contact_info_message import ContactInfoMessage
from openapi_client.models.contact_request_task_message import ContactRequestTaskMessage
from openapi_client.models.contact_request_task_post_message import ContactRequestTaskPostMessage
from openapi_client.models.contact_request_task_put_message import ContactRequestTaskPutMessage
from openapi_client.models.cosigner_message import CosignerMessage
from openapi_client.models.created_by_user_message import CreatedByUserMessage
from openapi_client.models.credit_recurring_transaction_post_message import CreditRecurringTransactionPostMessage
from openapi_client.models.deposit_detail_message import DepositDetailMessage
from openapi_client.models.eft_payments_message import EFTPaymentsMessage
from openapi_client.models.eft_payments_put_message import EFTPaymentsPutMessage
from openapi_client.models.e_pay_settings_message import EPaySettingsMessage
from openapi_client.models.e_pay_settings_put_message import EPaySettingsPutMessage
from openapi_client.models.electronic_payments_message import ElectronicPaymentsMessage
from openapi_client.models.email_message import EmailMessage
from openapi_client.models.email_post_message import EmailPostMessage
from openapi_client.models.email_recipient_message import EmailRecipientMessage
from openapi_client.models.email_sender_message import EmailSenderMessage
from openapi_client.models.emergency_contact_message import EmergencyContactMessage
from openapi_client.models.file_category_message import FileCategoryMessage
from openapi_client.models.file_category_post_message import FileCategoryPostMessage
from openapi_client.models.file_category_put_message import FileCategoryPutMessage
from openapi_client.models.file_download_message import FileDownloadMessage
from openapi_client.models.file_entity_message import FileEntityMessage
from openapi_client.models.file_message import FileMessage
from openapi_client.models.file_name_post_message import FileNamePostMessage
from openapi_client.models.file_put_message import FilePutMessage
from openapi_client.models.file_sharing_account_message import FileSharingAccountMessage
from openapi_client.models.file_sharing_account_put_message import FileSharingAccountPutMessage
from openapi_client.models.file_sharing_association_message import FileSharingAssociationMessage
from openapi_client.models.file_sharing_association_owner_message import FileSharingAssociationOwnerMessage
from openapi_client.models.file_sharing_association_owner_put_message import FileSharingAssociationOwnerPutMessage
from openapi_client.models.file_sharing_association_put_message import FileSharingAssociationPutMessage
from openapi_client.models.file_sharing_association_unit_message import FileSharingAssociationUnitMessage
from openapi_client.models.file_sharing_association_unit_put_message import FileSharingAssociationUnitPutMessage
from openapi_client.models.file_sharing_committee_message import FileSharingCommitteeMessage
from openapi_client.models.file_sharing_committee_put_message import FileSharingCommitteePutMessage
from openapi_client.models.file_sharing_lease_message import FileSharingLeaseMessage
from openapi_client.models.file_sharing_lease_put_message import FileSharingLeasePutMessage
from openapi_client.models.file_sharing_message import FileSharingMessage
from openapi_client.models.file_sharing_ownership_account_message import FileSharingOwnershipAccountMessage
from openapi_client.models.file_sharing_ownership_account_put_message import FileSharingOwnershipAccountPutMessage
from openapi_client.models.file_sharing_put_message import FileSharingPutMessage
from openapi_client.models.file_sharing_rental_message import FileSharingRentalMessage
from openapi_client.models.file_sharing_rental_owner_message import FileSharingRentalOwnerMessage
from openapi_client.models.file_sharing_rental_owner_put_message import FileSharingRentalOwnerPutMessage
from openapi_client.models.file_sharing_rental_put_message import FileSharingRentalPutMessage
from openapi_client.models.file_sharing_rental_unit_mesage import FileSharingRentalUnitMesage
from openapi_client.models.file_sharing_rental_unit_put_mesage import FileSharingRentalUnitPutMesage
from openapi_client.models.file_sharing_tenant_message import FileSharingTenantMessage
from openapi_client.models.file_sharing_tenant_put_message import FileSharingTenantPutMessage
from openapi_client.models.file_sharing_vendor_message import FileSharingVendorMessage
from openapi_client.models.file_sharing_vendor_put_message import FileSharingVendorPutMessage
from openapi_client.models.file_upload_post_message import FileUploadPostMessage
from openapi_client.models.file_upload_ticket_message import FileUploadTicketMessage
from openapi_client.models.gl_account_balance_item_message import GLAccountBalanceItemMessage
from openapi_client.models.gl_account_balance_message import GLAccountBalanceMessage
from openapi_client.models.gl_account_message import GLAccountMessage
from openapi_client.models.gl_account_post_message import GLAccountPostMessage
from openapi_client.models.gl_account_put_message import GLAccountPutMessage
from openapi_client.models.gl_transaction_message_v1 import GLTransactionMessageV1
from openapi_client.models.general_journal_entry_line_save_message import GeneralJournalEntryLineSaveMessage
from openapi_client.models.general_journal_entry_post_message import GeneralJournalEntryPostMessage
from openapi_client.models.general_journal_entry_put_message import GeneralJournalEntryPutMessage
from openapi_client.models.general_ledger_entry_message import GeneralLedgerEntryMessage
from openapi_client.models.general_ledger_journal_line_message import GeneralLedgerJournalLineMessage
from openapi_client.models.general_ledger_journal_message import GeneralLedgerJournalMessage
from openapi_client.models.general_ledger_message import GeneralLedgerMessage
from openapi_client.models.general_ledger_transaction_message import GeneralLedgerTransactionMessage
from openapi_client.models.image_reorder_request_put_message import ImageReorderRequestPutMessage
from openapi_client.models.insured_tenant_message import InsuredTenantMessage
from openapi_client.models.internal_transaction_status_message import InternalTransactionStatusMessage
from openapi_client.models.java_script_encoder import JavaScriptEncoder
from openapi_client.models.journal_line_message import JournalLineMessage
from openapi_client.models.journal_message import JournalMessage
from openapi_client.models.json_patch_operation import JsonPatchOperation
from openapi_client.models.last_updated_by_user_message import LastUpdatedByUserMessage
from openapi_client.models.lease_account_detail_message import LeaseAccountDetailMessage
from openapi_client.models.lease_auto_allocated_payment_post_message import LeaseAutoAllocatedPaymentPostMessage
from openapi_client.models.lease_charge_line_message import LeaseChargeLineMessage
from openapi_client.models.lease_charge_line_save_message import LeaseChargeLineSaveMessage
from openapi_client.models.lease_charge_message import LeaseChargeMessage
from openapi_client.models.lease_charge_post_message import LeaseChargePostMessage
from openapi_client.models.lease_charge_put_message import LeaseChargePutMessage
from openapi_client.models.lease_charge_recurring_transaction_message import LeaseChargeRecurringTransactionMessage
from openapi_client.models.lease_cosigner_post_message import LeaseCosignerPostMessage
from openapi_client.models.lease_ledger_credit_line_post_message import LeaseLedgerCreditLinePostMessage
from openapi_client.models.lease_ledger_credit_post_message import LeaseLedgerCreditPostMessage
from openapi_client.models.lease_ledger_deposit_withholding_line_post_message import LeaseLedgerDepositWithholdingLinePostMessage
from openapi_client.models.lease_ledger_deposit_withholding_line_put_message import LeaseLedgerDepositWithholdingLinePutMessage
from openapi_client.models.lease_ledger_deposit_withholding_post_message import LeaseLedgerDepositWithholdingPostMessage
from openapi_client.models.lease_ledger_deposit_withholding_put_message import LeaseLedgerDepositWithholdingPutMessage
from openapi_client.models.lease_ledger_payment_line_save_message import LeaseLedgerPaymentLineSaveMessage
from openapi_client.models.lease_ledger_payment_post_message import LeaseLedgerPaymentPostMessage
from openapi_client.models.lease_ledger_payment_put_message import LeaseLedgerPaymentPutMessage
from openapi_client.models.lease_ledger_refund_line_message import LeaseLedgerRefundLineMessage
from openapi_client.models.lease_ledger_refund_line_post_message import LeaseLedgerRefundLinePostMessage
from openapi_client.models.lease_ledger_refund_message import LeaseLedgerRefundMessage
from openapi_client.models.lease_ledger_refund_post_message import LeaseLedgerRefundPostMessage
from openapi_client.models.lease_ledger_reverse_payment_nsf_charge_post_message import LeaseLedgerReversePaymentNSFChargePostMessage
from openapi_client.models.lease_ledger_reverse_payment_other_bank_charge_post_message import LeaseLedgerReversePaymentOtherBankChargePostMessage
from openapi_client.models.lease_ledger_reverse_payment_post_message import LeaseLedgerReversePaymentPostMessage
from openapi_client.models.lease_message import LeaseMessage
from openapi_client.models.lease_move_out_data_message import LeaseMoveOutDataMessage
from openapi_client.models.lease_move_out_data_post_message import LeaseMoveOutDataPostMessage
from openapi_client.models.lease_outstanding_balance_message import LeaseOutstandingBalanceMessage
from openapi_client.models.lease_post_message import LeasePostMessage
from openapi_client.models.lease_put_message import LeasePutMessage
from openapi_client.models.lease_recurring_credit_message import LeaseRecurringCreditMessage
from openapi_client.models.lease_recurring_payment_message import LeaseRecurringPaymentMessage
from openapi_client.models.lease_renewal_message import LeaseRenewalMessage
from openapi_client.models.lease_renewal_post_message import LeaseRenewalPostMessage
from openapi_client.models.lease_rent_charge_message import LeaseRentChargeMessage
from openapi_client.models.lease_rent_charge_post_message import LeaseRentChargePostMessage
from openapi_client.models.lease_rent_message import LeaseRentMessage
from openapi_client.models.lease_rent_post_message import LeaseRentPostMessage
from openapi_client.models.lease_security_deposit_post_message import LeaseSecurityDepositPostMessage
from openapi_client.models.lease_tenant_message import LeaseTenantMessage
from openapi_client.models.lease_transaction_message import LeaseTransactionMessage
from openapi_client.models.listing_contact_message import ListingContactMessage
from openapi_client.models.listing_contact_save_message import ListingContactSaveMessage
from openapi_client.models.listing_entity_file_post_message import ListingEntityFilePostMessage
from openapi_client.models.listing_file_message import ListingFileMessage
from openapi_client.models.listing_message import ListingMessage
from openapi_client.models.listing_property_message import ListingPropertyMessage
from openapi_client.models.listing_put_message import ListingPutMessage
from openapi_client.models.listing_unit_message import ListingUnitMessage
from openapi_client.models.lock_period_settings_global_message import LockPeriodSettingsGlobalMessage
from openapi_client.models.lock_period_settings_overrides_message import LockPeriodSettingsOverridesMessage
from openapi_client.models.logged_by_staff_user_message import LoggedByStaffUserMessage
from openapi_client.models.lookup_message import LookupMessage
from openapi_client.models.mailing_template_message import MailingTemplateMessage
from openapi_client.models.meter_reading_detail_message import MeterReadingDetailMessage
from openapi_client.models.meter_reading_detail_put_message import MeterReadingDetailPutMessage
from openapi_client.models.meter_reading_details_message import MeterReadingDetailsMessage
from openapi_client.models.meter_reading_details_put_message import MeterReadingDetailsPutMessage
from openapi_client.models.meter_reading_message import MeterReadingMessage
from openapi_client.models.multiple_bill_payments_post_message import MultipleBillPaymentsPostMessage
from openapi_client.models.note_message import NoteMessage
from openapi_client.models.note_post_message import NotePostMessage
from openapi_client.models.note_put_message import NotePutMessage
from openapi_client.models.offline_payments_message import OfflinePaymentsMessage
from openapi_client.models.offline_payments_put_message import OfflinePaymentsPutMessage
from openapi_client.models.outstanding_balances_line_message import OutstandingBalancesLineMessage
from openapi_client.models.ownership_account_auto_allocated_payment_post_message import OwnershipAccountAutoAllocatedPaymentPostMessage
from openapi_client.models.ownership_account_charge_recurring_transaction_message import OwnershipAccountChargeRecurringTransactionMessage
from openapi_client.models.ownership_account_credit_line_post_message import OwnershipAccountCreditLinePostMessage
from openapi_client.models.ownership_account_credit_post_message import OwnershipAccountCreditPostMessage
from openapi_client.models.ownership_account_deposit_withholding_line_post_message import OwnershipAccountDepositWithholdingLinePostMessage
from openapi_client.models.ownership_account_deposit_withholding_line_put_message import OwnershipAccountDepositWithholdingLinePutMessage
from openapi_client.models.ownership_account_deposit_withholding_post_message import OwnershipAccountDepositWithholdingPostMessage
from openapi_client.models.ownership_account_deposit_withholding_put_message import OwnershipAccountDepositWithholdingPutMessage
from openapi_client.models.ownership_account_ledger_charge_line_message import OwnershipAccountLedgerChargeLineMessage
from openapi_client.models.ownership_account_ledger_charge_lines_put_message import OwnershipAccountLedgerChargeLinesPutMessage
from openapi_client.models.ownership_account_ledger_charge_lines_save_message import OwnershipAccountLedgerChargeLinesSaveMessage
from openapi_client.models.ownership_account_ledger_charge_message import OwnershipAccountLedgerChargeMessage
from openapi_client.models.ownership_account_ledger_charge_post_message import OwnershipAccountLedgerChargePostMessage
from openapi_client.models.ownership_account_ledger_charge_put_message import OwnershipAccountLedgerChargePutMessage
from openapi_client.models.ownership_account_ledger_payment_line_save_message import OwnershipAccountLedgerPaymentLineSaveMessage
from openapi_client.models.ownership_account_ledger_payment_post_message import OwnershipAccountLedgerPaymentPostMessage
from openapi_client.models.ownership_account_ledger_payment_put_message import OwnershipAccountLedgerPaymentPutMessage
from openapi_client.models.ownership_account_outstanding_balance_message import OwnershipAccountOutstandingBalanceMessage
from openapi_client.models.ownership_account_recurring_credit_message import OwnershipAccountRecurringCreditMessage
from openapi_client.models.ownership_account_recurring_payment_message import OwnershipAccountRecurringPaymentMessage
from openapi_client.models.ownership_account_refund_line_message import OwnershipAccountRefundLineMessage
from openapi_client.models.ownership_account_refund_lines_post_message import OwnershipAccountRefundLinesPostMessage
from openapi_client.models.ownership_account_refund_message import OwnershipAccountRefundMessage
from openapi_client.models.ownership_account_refund_post_message import OwnershipAccountRefundPostMessage
from openapi_client.models.ownership_account_transaction_message import OwnershipAccountTransactionMessage
from openapi_client.models.paid_by_message import PaidByMessage
from openapi_client.models.partial_payment_settings_message import PartialPaymentSettingsMessage
from openapi_client.models.partial_payment_settings_patch_message import PartialPaymentSettingsPatchMessage
from openapi_client.models.participant_message import ParticipantMessage
from openapi_client.models.participant_resource_message import ParticipantResourceMessage
from openapi_client.models.payee_message import PayeeMessage
from openapi_client.models.payment_detail_message import PaymentDetailMessage
from openapi_client.models.payment_recurring_transaction_post_message import PaymentRecurringTransactionPostMessage
from openapi_client.models.payment_transactions_message import PaymentTransactionsMessage
from openapi_client.models.phone_log_message import PhoneLogMessage
from openapi_client.models.phone_log_participant_post_message import PhoneLogParticipantPostMessage
from openapi_client.models.phone_log_participant_unit_agreement_post_message import PhoneLogParticipantUnitAgreementPostMessage
from openapi_client.models.phone_log_post_message import PhoneLogPostMessage
from openapi_client.models.phone_log_put_message import PhoneLogPutMessage
from openapi_client.models.phone_number_message import PhoneNumberMessage
from openapi_client.models.phone_numbers_message import PhoneNumbersMessage
from openapi_client.models.property_group_message import PropertyGroupMessage
from openapi_client.models.property_group_post_message import PropertyGroupPostMessage
from openapi_client.models.property_group_put_message import PropertyGroupPutMessage
from openapi_client.models.property_manager_message import PropertyManagerMessage
from openapi_client.models.property_message import PropertyMessage
from openapi_client.models.recurring_transaction_line_message import RecurringTransactionLineMessage
from openapi_client.models.recurring_transaction_line_post_message import RecurringTransactionLinePostMessage
from openapi_client.models.recurring_transaction_message import RecurringTransactionMessage
from openapi_client.models.rent_schedule_charge_post_message import RentScheduleChargePostMessage
from openapi_client.models.rent_schedule_charge_put_message import RentScheduleChargePutMessage
from openapi_client.models.rent_schedule_post_message import RentSchedulePostMessage
from openapi_client.models.rent_schedule_put_message import RentSchedulePutMessage
from openapi_client.models.rental_appliance_message import RentalApplianceMessage
from openapi_client.models.rental_appliance_post_message import RentalAppliancePostMessage
from openapi_client.models.rental_appliance_put_message import RentalAppliancePutMessage
from openapi_client.models.rental_appliance_service_history_message import RentalApplianceServiceHistoryMessage
from openapi_client.models.rental_appliance_service_history_post_message import RentalApplianceServiceHistoryPostMessage
from openapi_client.models.rental_features_message import RentalFeaturesMessage
from openapi_client.models.rental_features_put_message import RentalFeaturesPutMessage
from openapi_client.models.rental_image_message import RentalImageMessage
from openapi_client.models.rental_image_put_message import RentalImagePutMessage
from openapi_client.models.rental_message import RentalMessage
from openapi_client.models.rental_owner_contribution_data_message import RentalOwnerContributionDataMessage
from openapi_client.models.rental_owner_contribution_data_put_message import RentalOwnerContributionDataPutMessage
from openapi_client.models.rental_owner_contribution_message import RentalOwnerContributionMessage
from openapi_client.models.rental_owner_contribution_put_message import RentalOwnerContributionPutMessage
from openapi_client.models.rental_owner_contribution_reminder_message import RentalOwnerContributionReminderMessage
from openapi_client.models.rental_owner_contribution_reminder_put_message import RentalOwnerContributionReminderPutMessage
from openapi_client.models.rental_owner_message import RentalOwnerMessage
from openapi_client.models.rental_owner_post_message import RentalOwnerPostMessage
from openapi_client.models.rental_owner_put_message import RentalOwnerPutMessage
from openapi_client.models.rental_owner_request_task_message import RentalOwnerRequestTaskMessage
from openapi_client.models.rental_owner_request_task_post_message import RentalOwnerRequestTaskPostMessage
from openapi_client.models.rental_owner_request_task_put_message import RentalOwnerRequestTaskPutMessage
from openapi_client.models.rental_owner_tax_information_message import RentalOwnerTaxInformationMessage
from openapi_client.models.rental_preferred_vendor_message import RentalPreferredVendorMessage
from openapi_client.models.rental_preferred_vendor_put_message import RentalPreferredVendorPutMessage
from openapi_client.models.rental_property_post_message import RentalPropertyPostMessage
from openapi_client.models.rental_property_put_message import RentalPropertyPutMessage
from openapi_client.models.rental_property_unit_post_message import RentalPropertyUnitPostMessage
from openapi_client.models.rental_tenant_post_message import RentalTenantPostMessage
from openapi_client.models.rental_tenant_put_message import RentalTenantPutMessage
from openapi_client.models.rental_tenant_renewal_post_message import RentalTenantRenewalPostMessage
from openapi_client.models.rental_unit_features_message import RentalUnitFeaturesMessage
from openapi_client.models.rental_unit_features_put_message import RentalUnitFeaturesPutMessage
from openapi_client.models.rental_unit_image_message import RentalUnitImageMessage
from openapi_client.models.rental_unit_image_put_message import RentalUnitImagePutMessage
from openapi_client.models.rental_unit_message import RentalUnitMessage
from openapi_client.models.rental_unit_put_message import RentalUnitPutMessage
from openapi_client.models.rental_units_post_message import RentalUnitsPostMessage
from openapi_client.models.renters_insurance_policy_message import RentersInsurancePolicyMessage
from openapi_client.models.requested_by_user_entity_message import RequestedByUserEntityMessage
from openapi_client.models.resident_center_user_message import ResidentCenterUserMessage
from openapi_client.models.resident_center_user_reference_message import ResidentCenterUserReferenceMessage
from openapi_client.models.resident_request_task_message import ResidentRequestTaskMessage
from openapi_client.models.resident_request_task_post_message import ResidentRequestTaskPostMessage
from openapi_client.models.resident_request_task_put_message import ResidentRequestTaskPutMessage
from openapi_client.models.retail_cash_property_message import RetailCashPropertyMessage
from openapi_client.models.retail_cash_unit_message import RetailCashUnitMessage
from openapi_client.models.retail_cash_user_data_message import RetailCashUserDataMessage
from openapi_client.models.retail_cash_user_message import RetailCashUserMessage
from openapi_client.models.retail_cash_user_put_message import RetailCashUserPutMessage
from openapi_client.models.save_address_message import SaveAddressMessage
from openapi_client.models.save_emergency_contact_message import SaveEmergencyContactMessage
from openapi_client.models.task_category_message import TaskCategoryMessage
from openapi_client.models.task_category_put_message import TaskCategoryPutMessage
from openapi_client.models.task_category_response_message import TaskCategoryResponseMessage
from openapi_client.models.task_category_save_message import TaskCategorySaveMessage
from openapi_client.models.task_history_file_message import TaskHistoryFileMessage
from openapi_client.models.task_history_file_upload_post_message import TaskHistoryFileUploadPostMessage
from openapi_client.models.task_history_message import TaskHistoryMessage
from openapi_client.models.task_history_put_message import TaskHistoryPutMessage
from openapi_client.models.task_history_user_message import TaskHistoryUserMessage
from openapi_client.models.task_sub_category_message import TaskSubCategoryMessage
from openapi_client.models.tax_information_post_message import TaxInformationPostMessage
from openapi_client.models.tax_information_save_message import TaxInformationSaveMessage
from openapi_client.models.tenant_message import TenantMessage
from openapi_client.models.to_do_task_message import ToDoTaskMessage
from openapi_client.models.to_do_task_post_message import ToDoTaskPostMessage
from openapi_client.models.to_do_task_put_message import ToDoTaskPutMessage
from openapi_client.models.undeposited_funds_message import UndepositedFundsMessage
from openapi_client.models.unit_agreement_message import UnitAgreementMessage
from openapi_client.models.unit_entity_message import UnitEntityMessage
from openapi_client.models.user_message import UserMessage
from openapi_client.models.user_role_message import UserRoleMessage
from openapi_client.models.vehicle_message import VehicleMessage
from openapi_client.models.vendor_category_message import VendorCategoryMessage
from openapi_client.models.vendor_category_save_message import VendorCategorySaveMessage
from openapi_client.models.vendor_credit_line_item_message import VendorCreditLineItemMessage
from openapi_client.models.vendor_credit_line_item_post_message import VendorCreditLineItemPostMessage
from openapi_client.models.vendor_credit_message import VendorCreditMessage
from openapi_client.models.vendor_credit_post_message import VendorCreditPostMessage
from openapi_client.models.vendor_insurance_message import VendorInsuranceMessage
from openapi_client.models.vendor_insurance_save_message import VendorInsuranceSaveMessage
from openapi_client.models.vendor_message import VendorMessage
from openapi_client.models.vendor_post_message import VendorPostMessage
from openapi_client.models.vendor_put_message import VendorPutMessage
from openapi_client.models.vendor_refund_line_message import VendorRefundLineMessage
from openapi_client.models.vendor_refund_line_post_message import VendorRefundLinePostMessage
from openapi_client.models.vendor_refund_message import VendorRefundMessage
from openapi_client.models.vendor_refund_post_message import VendorRefundPostMessage
from openapi_client.models.vendor_tax_information_message import VendorTaxInformationMessage
from openapi_client.models.vendor_transaction_message import VendorTransactionMessage
from openapi_client.models.video_link_request_post_message import VideoLinkRequestPostMessage
from openapi_client.models.work_order_entry_contact_message import WorkOrderEntryContactMessage
from openapi_client.models.work_order_entry_contact_resource_message import WorkOrderEntryContactResourceMessage
from openapi_client.models.work_order_line_item_message import WorkOrderLineItemMessage
from openapi_client.models.work_order_line_item_save_message import WorkOrderLineItemSaveMessage
from openapi_client.models.work_order_message import WorkOrderMessage
from openapi_client.models.work_order_post_message import WorkOrderPostMessage
from openapi_client.models.work_order_put_message import WorkOrderPutMessage
from openapi_client.models.work_order_task_message import WorkOrderTaskMessage
from openapi_client.models.work_order_task_post_message import WorkOrderTaskPostMessage

